# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29f77b4f55e471f668fade7936ada2d5c5513ebba4ded6fb37e46cf68e7a30c3d9aa70a685079ec1ab49c8586fdb7f5e2054f26c494959a1dd6a0a1844f067cd

test:
  secret_key_base: 1f48468eba6e4f8989d8f8e08c3185e4040ca6dbf6e45c5c6caba44d14cda74302ae03baa8e4ad5345c4b2a6a62e927f0acff115f88eada9ddfcfc928f7fe99f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
